### ISSUE TITLE
nnUnet and DeepScan not working when running FeTS_CLI

### ISSUE THREAD

**Issue by umgpy** [FETS-AI/Front-End#21]
**Describe the bug**
DeepMedic runs since it is CPU based but DeepScan and nnUnet gives error while running

**To Reproduce**
1. Have CUDA version 10.0
2. Run FeTS_CLI with tags -g 1 and -t 0
3. After test session finishes and nnUnet starts.
4. Gives the following error

```bash
== Starting inference using nnUNet...
=== 
=== Command to run: 
/home/xxx/Documents/xxx/FeTS/squashfs-root/usr/bin//OpenFederatedLearning//venv/bin/python /home/xxx/Documents/xxx/FeTS/squashfs-root/usr/bin//OpenFederatedLearning//bin/run_inference_from_flplan.py  -d ../../../FeTS_data/Output_BRaTs/DataForFeTS/ -md cuda -ld ../../../FeTS_data/Output_BRaTs/DataForFeTS//logs -ip 3002 -nmwf /home/xxx/Documents/xxx/FeTS/squashfs-root/usr/bin/../data//fets/nnunet -p nnunet_inference.yaml -pwai
===
Logging configuration file [logging.yaml] not found.
2021-02-01 13:51:34 DGX-Station openfl.flplan[34879] INFO Using FLPlan defaults for section 'network_object_init' from file '/home/xxx/Documents/xxx/FeTS/squashfs-root/usr/bin/OpenFederatedLearning/bin/federations/plans/defaults/network.yaml'
2021-02-01 13:51:34 DGX-Station openfl.flplan[34879] INFO After hashing /home/xxx/Documents/xxx/FeTS/squashfs-root/usr/bin/OpenFederatedLearning/bin/federations/plans/nnunet_inference.yaml, hash is 5141593c394d4377c304400444b8d62b
2021-02-01 13:51:34 DGX-Station openfl.flplan[34879] INFO After hashing /home/xxx/Documents/xxx/FeTS/squashfs-root/usr/bin/OpenFederatedLearning/bin/federations/plans/defaults/network.yaml, hash is bf5f909c1e1fb5d53f0013289ba246b6
2021-02-01 13:51:34 DGX-Station openfl.flplan[34879] INFO Parsed plan:
aggregator_object_init:
  init_kwargs:
    aggregator_uuid: aggregator_nnunet_inference_bf5f909c
    federation_uuid: nnunet_inference_bf5f909c
collaborator_object_init:
  init_kwargs:
    aggregator_uuid: aggregator_nnunet_inference_bf5f909c
    federation_uuid: nnunet_inference_bf5f909c
data_object_init:
  class_to_init: fets.data.pytorch.file_lists_data.FileListsData
  init_kwargs:
    feature_modes:
    - _t1.nii.gz
    - _t2.nii.gz
    - _flair.nii.gz
    - _t1ce.nii.gz
hash: bf5f909c1e1fb5d53f0013289ba246b6
inference:
  allowed: true
  init_kwargs: {}
  kwargs:
    output_file_tag: ''
model_object_init:
  class_to_init: fets.models.pytorch.nnunet.nnunet.NNUnetInferenceOnlyModel
  init_kwargs: {}
network_object_init:
  auto_port: false
  cert_folder: pki
  defaults_file: defaults/network.yaml
  hash_salt: Anything you want. Make it unique
  init_kwargs:
    agg_addr: sbia-pc103.med.upenn.edu
    agg_port: 50051
    disable_client_auth: false
    disable_tls: false



Please cite the following paper when using nnUNet:

Isensee, F., Jaeger, P.F., Kohl, S.A.A. et al. "nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation." Nat Methods (2020). https://doi.org/10.1038/s41592-020-01008-z


If you have questions or suggestions, feel free to open an issue at https://github.com/MIC-DKFZ/nnUNet

nnUNet_raw_data_base is not defined and nnU-Net can only be used on data for which preprocessed files are already present on your system. nnU-Net cannot be used for experiment planning and preprocessing like this. If this is not intended, please read nnunet/paths.md for information on how to set this up properly.
nnUNet_preprocessed is not defined and nnU-Net can not be used for preprocessing or training. If this is not intended, please read nnunet/pathy.md for information on how to set this up.
RESULTS_FOLDER is not defined and nnU-Net cannot be used for training or inference. If this is not intended behavior, please read nnunet/paths.md for information on how to set this up
emptying cuda cache
loading parameters for folds, (0, 1, 2, 3, 4)
/home/xxx/Documents/xxx/FeTS/squashfs-root/usr/bin/OpenFederatedLearning/venv/lib/python3.7/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 10000). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
using the following model files:  ['/home/xxx/Documents/xxx/FeTS/squashfs-root/usr/bin/../data//fets/nnunet/nnUNetTrainerV2BraTSRegions_DA3_BN_BD__nnUNetPlansv2.1_bs5/fold_0/model_final_checkpoint.model', '/home/xxx/Documents/xxx/FeTS/squashfs-root/usr/bin/../data//fets/nnunet/nnUNetTrainerV2BraTSRegions_DA3_BN_BD__nnUNetPlansv2.1_bs5/fold_1/model_final_checkpoint.model', '/home/xxx/Documents/xxx/FeTS/squashfs-root/usr/bin/../data//fets/nnunet/nnUNetTrainerV2BraTSRegions_DA3_BN_BD__nnUNetPlansv2.1_bs5/fold_2/model_final_checkpoint.model', '/home/xxx/Documents/xxx/FeTS/squashfs-root/usr/bin/../data//fets/nnunet/nnUNetTrainerV2BraTSRegions_DA3_BN_BD__nnUNetPlansv2.1_bs5/fold_3/model_final_checkpoint.model', '/home/xxx/Documents/xxx/FeTS/squashfs-root/usr/bin/../data//fets/nnunet/nnUNetTrainerV2BraTSRegions_DA3_BN_BD__nnUNetPlansv2.1_bs5/fold_4/model_final_checkpoint.model']
starting preprocessing generator
starting prediction...
preprocessing ../../../FeTS_data/Output_BRaTs/DataForFeTS/nnUNetTrainerV2BraTSRegions_DA3_BN_BD__nnUNetPlansv2.1_bs5/3002_nnunet_seg.nii.gz
using preprocessor GenericPreprocessor
before crop: (4, 155, 240, 240) after crop: (4, 149, 159, 124) spacing: [1. 1. 1.] 

no resampling necessary
no resampling necessary
before: {'spacing': array([1., 1., 1.]), 'spacing_transposed': array([1., 1., 1.]), 'data.shape (data is transposed)': (4, 149, 159, 124)} 
after:  {'spacing': array([1., 1., 1.]), 'data.shape (data is resampled)': (4, 149, 159, 124)} 

(4, 149, 159, 124)
This worker has ended successfully, no errors to report
predicting ../../../FeTS_data/Output_BRaTs/DataForFeTS/nnUNetTrainerV2BraTSRegions_DA3_BN_BD__nnUNetPlansv2.1_bs5/3002_nnunet_seg.nii.gz
debug: mirroring True mirror_axes (0, 1, 2)
/home/xxx/Documents/xxx/FeTS/squashfs-root/usr/bin/OpenFederatedLearning/venv/lib/python3.7/site-packages/torch/cuda/amp/autocast_mode.py:114: UserWarning: torch.cuda.amp.autocast only affects CUDA ops, but CUDA is not available.  Disabling.
  warnings.warn("torch.cuda.amp.autocast only affects CUDA ops, but CUDA is not available.  Disabling.")
step_size: 0.5
do mirror: True
data shape: (4, 149, 159, 128)
patch size: [128 128 128]
steps (x, y, and z): [[0, 21], [0, 31], [0]]
number of tiles: 4
computing Gaussian
Traceback (most recent call last):
  File "/home/xxx/Documents/xxx/FeTS/squashfs-root/usr/bin//OpenFederatedLearning//bin/run_inference_from_flplan.py", line 144, in <module>
    main(**vars(args))
  File "/home/xxx/Documents/xxx/FeTS/squashfs-root/usr/bin//OpenFederatedLearning//bin/run_inference_from_flplan.py", line 124, in main
    model.run_inference_and_store_results(**inference_kwargs)
  File "/home/xxx/Documents/xxx/FeTS/squashfs-root/usr/bin/OpenFederatedLearning/venv/lib/python3.7/site-packages/fets/models/pytorch/nnunet/nnunet.py", line 153, in run_inference_and_store_results
    step_size=0.5)
  File "/home/xxx/Documents/xxx/FeTS/squashfs-root/usr/bin/OpenFederatedLearning/venv/lib/python3.7/site-packages/nnunet/inference/predict.py", line 218, in predict_cases
    mixed_precision=mixed_precision)[1][None])
  File "/home/xxx/Documents/xxx/FeTS/squashfs-root/usr/bin/OpenFederatedLearning/venv/lib/python3.7/site-packages/nnunet/training/network_training/nnUNetTrainerV2.py", line 217, in predict_preprocessed_data_return_seg_and_softmax
    mixed_precision=mixed_precision)
  File "/home/xxx/Documents/xxx/FeTS/squashfs-root/usr/bin/OpenFederatedLearning/venv/lib/python3.7/site-packages/nnunet/training/network_training/nnUNetTrainer.py", line 521, in predict_preprocessed_data_return_seg_and_softmax
    mixed_precision=mixed_precision)
  File "/home/xxx/Documents/xxx/FeTS/squashfs-root/usr/bin/OpenFederatedLearning/venv/lib/python3.7/site-packages/nnunet/network_architecture/neural_network.py", line 150, in predict_3D
    verbose=verbose)
  File "/home/xxx/Documents/xxx/FeTS/squashfs-root/usr/bin/OpenFederatedLearning/venv/lib/python3.7/site-packages/nnunet/network_architecture/neural_network.py", line 333, in _internal_predict_3D_3Dconv_tiled
    non_blocking=True)
  File "/home/xxx/Documents/xxx/FeTS/squashfs-root/usr/bin/OpenFederatedLearning/venv/lib/python3.7/site-packages/torch/cuda/__init__.py", line 172, in _lazy_init
    torch._C._cuda_init()
RuntimeError: The NVIDIA driver on your system is too old (found version 10000). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver.
=== Couldn't complete the inference for nnunet for subject 3002.
== Starting label fusion...
```
5. While deepscan doesn't work even after passing it as a parameter to FeTS_CLI 

**Expected behavior**
nnUNet and Deepscan working

**Screenshots**

**FeTS Version**
0.0.2

**Desktop (please complete the following information):**
 - OS: Linux - Ubuntu 18.10
 - Version : CUDA 10.0, Driver Version: 410.104 

**Additional context**

> Pip output for OpenFederatedLearning vitrual environment

```bash
$ pip list
Package               Version     Location                                                                                                             
--------------------- ----------- ---------------------------------------------------------------------------------------------------------------------       
...    
nnunet                1.6.6       
...      
torch                 1.7.1       
torchaudio            0.7.2       
torchio               0.18.10     
torchsummary          1.5.1       
torchvision           0.5.0+cu100 
torchviz              0.0.1       
...   

```
> On loading torch in the venv python interpretor

```python
Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.cuda.current_device()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xxx/Documents/xxx/FeTS/squashfs-root/usr/bin/OpenFederatedLearning/venv/lib/python3.7/site-packages/torch/cuda/__init__.py", line 366, in current_device
    _lazy_init()
  File "/home/xxx/Documents/xxx/FeTS/squashfs-root/usr/bin/OpenFederatedLearning/venv/lib/python3.7/site-packages/torch/cuda/__init__.py", line 172, in _lazy_init
    torch._C._cuda_init()
RuntimeError: The NVIDIA driver on your system is too old (found version 10000). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver.
>>> torch.cuda.is_available()
/home/xxx/Documents/xxx/FeTS/squashfs-root/usr/bin/OpenFederatedLearning/venv/lib/python3.7/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 10000). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
False

```
Requirements of nnUNet from the repository [https://github.com/MIC-DKFZ/nnUNet#installation](url)

>    Install PyTorch. You need at least version 1.6

Since PyTorch 1.7.1 that was installed with the binary is not working and PyTorch build for CUDA 10 is only available till torch version 1.4 #20 . Does that mean CUDA 10 is effectively not supported?  
Also how can I run DeepScan or check if it is installed since it is not running during inference?

**Comment by sarthakpati** [comment]
Hi @umgpy, this is probably something you need to check with the [PyTorch installation site](https://pytorch.org/get-started/locally/), as we don't do anything related to CUDA. As a reminder, although PyTorch does get installed, it is recommend to perform an installation based on your CUDA/driver versions. I am assuming that since you have CUDA 10.0 installed, the PyTorch installation for 9.2 would be appropriate:

```bash
pip install torch==1.7.1+cu92 torchvision==0.8.2+cu92 torchaudio==0.7.2 -f https://download.pytorch.org/whl/torch_stable.html
```

**Comment by umgpy** [comment]
Hi @sarthakpati  PyTorch installation for 9.2 worked. I had tired to see if 9.2 builds were forward compatible with CUDA 10 but couldn't find anything definite. Thanks for the help, segmentation is running now as intended.
