### ISSUE TITLE
CUDA

### ISSUE THREAD

**Issue by LisaGreutter** [FETS-AI/Front-End#56]
/home/neuropathoanalyser/FeTS-AI/squashfs-root/usr/bin/FeTS_CLI_Segment -d ~/niftis/niftis_sorted_all/DataForFeTS -a nnunet -g 0 -t 0
Using the following directory as logging directory: /home/neuropathoanalyser/niftis/niftis_sorted_all/DataForFeTS/logs
Starting subject directory iteration...
= Starting inference for subject: Patient_GA013_20160822
== Starting inference using nnUNet...
===
=== Command to run:
/home/neuropathoanalyser/FeTS-AI/squashfs-root/usr/bin//OpenFederatedLearning//venv/bin/python /home/neuropathoanalyser/FeTS-AI/squashfs-root/usr/bin//OpenFederatedLearning//bin/run_inference_from_flplan.py  -d /home/neuropathoanalyser/niftis/niftis_sorted_all/DataForFeTS -md cpu -ld /home/neuropathoanalyser/niftis/niftis_sorted_all/DataForFeTS/logs -ip Patient_GA013_20160822 -nmwf /home/neuropathoanalyser/FeTS-AI/squashfs-root/usr/bin/../data//fets/nnunet -p nnunet_inference.yaml -pwai
===
Logging configuration file [logging.yaml] not found.
2023-04-04 16:03:00 neuropathoanalyser-Op52a openfl.flplan[171529] INFO Using FLPlan defaults for section 'network_object_init' from file '/home/neuropathoanalyser/FeTS-AI/squashfs-root/usr/bin/OpenFederatedLearning/bin/federations/plans/defaults/network.yaml'
2023-04-04 16:03:00 neuropathoanalyser-Op52a openfl.flplan[171529] INFO After hashing /home/neuropathoanalyser/FeTS-AI/squashfs-root/usr/bin/OpenFederatedLearning/bin/federations/plans/nnunet_inference.yaml, hash is 5141593c394d4377c304400444b8d62b
2023-04-04 16:03:00 neuropathoanalyser-Op52a openfl.flplan[171529] INFO After hashing /home/neuropathoanalyser/FeTS-AI/squashfs-root/usr/bin/OpenFederatedLearning/bin/federations/plans/defaults/network.yaml, hash is c8e64bfbad2b85d67c65129c65d8a1b0
2023-04-04 16:03:00 neuropathoanalyser-Op52a openfl.flplan[171529] INFO Parsed plan:
aggregator_object_init:
  init_kwargs:
    aggregator_uuid: aggregator_nnunet_inference_c8e64bfb
    federation_uuid: nnunet_inference_c8e64bfb
collaborator_object_init:
  init_kwargs:
    aggregator_uuid: aggregator_nnunet_inference_c8e64bfb
    federation_uuid: nnunet_inference_c8e64bfb
data_object_init:
  class_to_init: fets.data.pytorch.file_lists_data.FileListsData
  init_kwargs:
    feature_modes:
    - _t1.nii.gz
    - _t2.nii.gz
    - _flair.nii.gz
    - _t1ce.nii.gz
hash: c8e64bfbad2b85d67c65129c65d8a1b0
inference:
  allowed: true
  init_kwargs: {}
  kwargs:
    output_file_tag: ''
model_object_init:
  class_to_init: fets.models.pytorch.nnunet.nnunet.NNUnetInferenceOnlyModel
  init_kwargs: {}
network_object_init:
  auto_port: false
  cert_folder: pki
  defaults_file: defaults/network.yaml
  hash_salt: Anything you want. Make it unique
  init_kwargs:
    agg_addr: sbia-pc103.med.upenn.edu
    agg_port: 50051
    disable_client_auth: false
    disable_tls: false

Please cite the following paper when using nnUNet:

Isensee, F., Jaeger, P.F., Kohl, S.A.A. et al. "nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation." Nat Methods (2020). https://doi.org/10.1038/s41592-020-01008-z

If you have questions or suggestions, feel free to open an issue at https://github.com/MIC-DKFZ/nnUNet

nnUNet_raw_data_base is not defined and nnU-Net can only be used on data for which preprocessed files are already present on your system. nnU-Net cannot be used for experiment planning and preprocessing like this. If this is not intended, please read nnunet/paths.md for information on how to set this up properly.
nnUNet_preprocessed is not defined and nnU-Net can not be used for preprocessing or training. If this is not intended, please read nnunet/pathy.md for information on how to set this up.
RESULTS_FOLDER is not defined and nnU-Net cannot be used for training or inference. If this is not intended behavior, please read nnunet/paths.md for information on how to set this up
emptying cuda cache
loading parameters for folds, (0, 1, 2, 3, 4)
using the following model files:  ['/home/neuropathoanalyser/FeTS-AI/squashfs-root/usr/bin/../data//fets/nnunet/nnUNetTrainerV2BraTSRegions_DA3_BN_BD__nnUNetPlansv2.1_bs5/fold_0/model_final_checkpoint.model', '/home/neuropathoanalyser/FeTS-AI/squashfs-root/usr/bin/../data//fets/nnunet/nnUNetTrainerV2BraTSRegions_DA3_BN_BD__nnUNetPlansv2.1_bs5/fold_1/model_final_checkpoint.model', '/home/neuropathoanalyser/FeTS-AI/squashfs-root/usr/bin/../data//fets/nnunet/nnUNetTrainerV2BraTSRegions_DA3_BN_BD__nnUNetPlansv2.1_bs5/fold_2/model_final_checkpoint.model', '/home/neuropathoanalyser/FeTS-AI/squashfs-root/usr/bin/../data//fets/nnunet/nnUNetTrainerV2BraTSRegions_DA3_BN_BD__nnUNetPlansv2.1_bs5/fold_3/model_final_checkpoint.model', '/home/neuropathoanalyser/FeTS-AI/squashfs-root/usr/bin/../data//fets/nnunet/nnUNetTrainerV2BraTSRegions_DA3_BN_BD__nnUNetPlansv2.1_bs5/fold_4/model_final_checkpoint.model']
starting preprocessing generator
starting prediction...
preprocessing /home/neuropathoanalyser/niftis/niftis_sorted_all/DataForFeTS/nnUNetTrainerV2BraTSRegions_DA3_BN_BD__nnUNetPlansv2.1_bs5/Patient_GA013_20160822_nnunet_seg.nii.gz
using preprocessor GenericPreprocessor
before crop: (4, 155, 240, 240) after crop: (4, 139, 168, 140) spacing: [1. 1. 1.]

no resampling necessary
no resampling necessary
before: {'spacing': array([1., 1., 1.]), 'spacing_transposed': array([1., 1., 1.]), 'data.shape (data is transposed)': (4, 139, 168, 140)}
after:  {'spacing': array([1., 1., 1.]), 'data.shape (data is resampled)': (4, 139, 168, 140)}

(4, 139, 168, 140)
This worker has ended successfully, no errors to report
predicting /home/neuropathoanalyser/niftis/niftis_sorted_all/DataForFeTS/nnUNetTrainerV2BraTSRegions_DA3_BN_BD__nnUNetPlansv2.1_bs5/Patient_GA013_20160822_nnunet_seg.nii.gz
debug: mirroring True mirror_axes (0, 1, 2)
/home/neuropathoanalyser/FeTS-AI/squashfs-root/usr/bin/OpenFederatedLearning/venv/lib/python3.7/site-packages/torch/cuda/amp/autocast_mode.py:114: UserWarning: torch.cuda.amp.autocast only affects CUDA ops, but CUDA is not available.  Disabling.
  warnings.warn("torch.cuda.amp.autocast only affects CUDA ops, but CUDA is not available.  Disabling.")
step_size: 0.5
do mirror: True
data shape: (4, 139, 168, 140)
patch size: [128 128 128]
steps (x, y, and z): [[0, 11], [0, 40], [0, 12]]
number of tiles: 8
computing Gaussian
Traceback (most recent call last):
  File "/home/neuropathoanalyser/FeTS-AI/squashfs-root/usr/bin//OpenFederatedLearning//bin/run_inference_from_flplan.py", line 142, in <module>
    main(**vars(args))
  File "/home/neuropathoanalyser/FeTS-AI/squashfs-root/usr/bin//OpenFederatedLearning//bin/run_inference_from_flplan.py", line 122, in main
    model.run_inference_and_store_results(**inference_kwargs)
  File "/home/neuropathoanalyser/FeTS-AI/squashfs-root/usr/bin/OpenFederatedLearning/venv/lib/python3.7/site-packages/fets/models/pytorch/nnunet/nnunet.py", line 153, in run_inference_and_store_results
    step_size=0.5)
  File "/home/neuropathoanalyser/FeTS-AI/squashfs-root/usr/bin/OpenFederatedLearning/venv/lib/python3.7/site-packages/nnunet/inference/predict.py", line 218, in predict_cases
    mixed_precision=mixed_precision)[1][None])
  File "/home/neuropathoanalyser/FeTS-AI/squashfs-root/usr/bin/OpenFederatedLearning/venv/lib/python3.7/site-packages/nnunet/training/network_training/nnUNetTrainerV2.py", line 217, in predict_preprocessed_data_return_seg_and_softmax
    mixed_precision=mixed_precision)
  File "/home/neuropathoanalyser/FeTS-AI/squashfs-root/usr/bin/OpenFederatedLearning/venv/lib/python3.7/site-packages/nnunet/training/network_training/nnUNetTrainer.py", line 521, in predict_preprocessed_data_return_seg_and_softmax
    mixed_precision=mixed_precision)
  File "/home/neuropathoanalyser/FeTS-AI/squashfs-root/usr/bin/OpenFederatedLearning/venv/lib/python3.7/site-packages/nnunet/network_architecture/neural_network.py", line 150, in predict_3D
    verbose=verbose)
  File "/home/neuropathoanalyser/FeTS-AI/squashfs-root/usr/bin/OpenFederatedLearning/venv/lib/python3.7/site-packages/nnunet/network_architecture/neural_network.py", line 333, in _internal_predict_3D_3Dconv_tiled
    non_blocking=True)
  File "/home/neuropathoanalyser/FeTS-AI/squashfs-root/usr/bin/OpenFederatedLearning/venv/lib/python3.7/site-packages/torch/cuda/__init__.py", line 172, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available
=== Couldn't complete the inference for nnunet for subject Patient_GA013_20160822.

**Comment by sarthakpati** [comment]
Hi,

Thank you for your interest in the FeTS Tool! It would be helpful if you could put your report in one of the pre-defined formats. For example, this is the one for a bug report:
https://github.com/FeTS-AI/Front-End/issues/new?assignees=&labels=&template=---bug-report.md&title=

Anyway, for your error, this seems to be the issue:
> RuntimeError: No CUDA GPUs are available

You do not have a GPU present on your machine.

**Comment by sarthakpati** [comment]
Superceded by #57
